### ISSUE TITLE
Issue with "Virginia Tech News" Name Record

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#116] opened 2015-11-27 07:19 UTC
Hi all, I've tried endlessly to correct an author name inconsistency in the VT News Collection (http://vtechworks.lib.vt.edu/handle/10919/19073), but to no avail. In short, there are two discrete name records for "Virginia Tech News" (dc.contributor.author). There are 159 total items authored by "Virginia Tech News" in this collection, and if you look at the author browse list or the author facet list, you'll see that there's one group of 35 "Virginia Tech News" items, and another group of 124 "Virginia Tech News" items. I've tried reconciling the name IDs (hashes) in Google Refine, as well as removing the name IDs altogether and re-reconciling the names, but neither strategy has worked. I'd also like to note that there are no leading/trailing whitespaces (or consecutive whitespaces) that are causing this problem. Any help would be appreciated. Thanks so much!

**Comment by alawvt** [comment] 2015-11-30 21:19
From the "Filter by: Author" list for "V," http://vtechworks.lib.vt.edu/handle/10919/19073/search-filter?field=author&starts_with=v,

If I select "Virginia Tech News (35)," http://vtechworks.lib.vt.edu/handle/10919/19073/discover?field=author&filtertype=author&filter_relational_operator=equals&filter=Virginia+Tech+News, the search results filter is labeled "Virginia Tech News" and there are 159 results.

If I select  "Virginia Tech News (124)," http://vtechworks.lib.vt.edu/handle/10919/19073/discover?field=author&filtertype=author&filter_relational_operator=authority&filter=d264a999-2f9f-40f3-92dd-75a2c55e38fe, the search results filter is labeled "d264a999-2f9f-40f3-92dd-75a2c55e38fe" and there are 124 results. (Also, just hovering over the URL in the list, you can see this long filter name, rather than "Virginia Tech News."

The group of 124 results is a subset of the group of 159 results. The long filter label looks like a DSpace author identifier. 

The first set is labeled 35 but there are 159 results. However, 159-124=35, so it seems like there is a math error in there!

An item in both groups, http://hdl.handle.net/10919/59641, or http://vtechworks.lib.vt.edu/admin/item?administrative-continue=4c0d2124830d134359155c513f2d108764633d52&submit_metadata, has the author identifier, d264a999-2f9f-40f3-92dd-75a2c55e38fe. To the left of the author id is an "x" with the tooltip, "Confidence was never recorded for this value." In the exported metadata for the item, dc.contributer.author[en_US]="Virginia Tech News::d264a999-2f9f-40f3-92dd-75a2c55e38fe::600." I exported the metadata for another item in both groups and it also had a author identifier confidence of 600.

An item in the collection of 159 but not in the group of 124, http://hdl.handle.net/10919/21360, or http://vtechworks.lib.vt.edu/admin/item?administrative-continue=298458153934285359552d87483f42818a440268&submit_metadata, has the same author identifier, d264a999-2f9f-40f3-92dd-75a2c55e38fe. To the left of the author id is a gear icon with the tooltip, "Value is singular and valid but has not been seen and accepted by a human so it is uncertain." In the exported metadata for the item, dc.contributer.author[en_US]="Virginia Tech News::d264a999-2f9f-40f3-92dd-75a2c55e38fe::500." I exported the metadata for another items in the group of 159 but not in the group of 124 and it also had a author identifier confidence of 500.

The author identifier confidence (500 vs 600) is an indication of the confidence of the identifier to the item.

DSpace 5 Wiki -- Authority Control of Metadata Values, https://wiki.duraspace.org/display/DSDOC5x/Authority+Control+of+Metadata+Values has incomplete documentation.

DSpace Development Areas -- Authority Control of Metadata Values, https://wiki.duraspace.org/display/DSPACE/Authority+Control+of+Metadata+Values, has more documentation but may not be all implemented.

"Display and Crosswalk

Every metadata value potentially includes values for an authority key, and an authority confidence. They are only present when the field is under authority control, and when there is an actual authority value, otherwise they are absent (e.g. in the DIM XML representation) or null."

"Search

The support for authority control in search is very subtle:

For every search index that includes an authority-controlled metadata field, another index is automatically created just for the authority values. It is given the name of the index followed by "authority". Note that its search terms are the raw authority keys, _not the text metadata values – those are still indexed normally."

"Confidence Values

There are symbolic constants (and corresponding String symblic names) for the confidence levels defined in the Choices class:

    ACCEPTED - This authority value has been confirmed as accurate by an interactive user or authoritative policy
    UNCERTAIN - Authority value is singular and valid but has not been seen and accepted by a human, so its provenance is uncertain
    AMBIGUOUS - There are multiple matching authority values of equal validity
    NOTFOUND - There are no matching answers from the authority
    FAILED - The authority encountered an internal failure in trying to match the value
    REJECTED - The authority recommends this submission be rejected
    NOVALUE - No reasonable confidence value is available
    UNUSED - No confidence value has been set (default value in the DB table)"

I don't find any other author identifiers In a quick sampling of the other "Filter by: Author" list entries for this collection.

I don't know why the confidence of one group would be different than the other and why that would cause the filter to display the identifier rather than the name.

**Comment by amandafrench** [comment] 2015-12-01 16:23
Hi @alawvt and @mello99 -- this sounds like a great candidate for querying the dspace-tech listserv about; I feel like we don't participate enough there. I chime in occasionally but have been too busy to read it much lately.

**Comment by amandafrench** [comment] 2015-12-01 16:24
Also I don't think we've actually implemented authority control on any elements, though my understanding might be imperfect -- it's something I want to do, but it's not super high priority.

**Comment by alawvt** [comment] 2015-12-01 16:26
I think by turning on ORCID, we've turned on authority control for the dc.contributor.author field.

**Comment by alawvt** [comment] 2015-12-01 16:27
I agree about querying the DSpace tech listserv.

**Comment by amandafrench** [comment] 2015-12-01 17:26
Oh, good point about ORCID, @alawvt. I wonder if that's what's causing those weird long strings.

**Comment by amandafrench** [comment] 2015-12-03 18:23
Assigning to @alawvt to report on DSpace Tech and/or in DSpace Jira: close it once it's reported.

**Comment by alawvt** [comment] 2015-12-07 21:11
Reported in DSpace DS-2938, Multiple dc.contributor.author facets have same authority value but different confidence value, also incorrect # of items, https://jira.duraspace.org/browse/DS-2938.

**Closed by alawvt** 2015-12-07 21:11 UTC
