### ISSUE TITLE
Create Elements XSL crosswalks

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#228] opened 2016-03-31 17:19 UTC
By Tuesday, 4/5. See links under "Elements Integration" on the VTechWorks Documentation wiki on git.it.vt.edu for links to current google Docs and Symplectic documentation.

**Comment by mello99** [comment] 2016-03-31 17:20
Noted, thanks!

**Comment by mello99** [comment] 2016-04-04 21:38
Uploaded test XSLT to GitHub - [it can be accessed at the following link](https://github.com/VTUL/vtechworks/blob/vt_5_x_dev/dspace/config/crosswalks/symplectic_xwalks_dspace_default.xsl).

**Comment by keithgee** [comment] 2016-04-04 22:04
@mello99 - the new crosswalk is now on VTechWorks pre-production.

**Comment by mello99** [comment] 2016-04-04 22:38
Hi, @keithgee , thanks for taking care of that so quickly. I was able to deposit a test item and while PPRD didn't break (hooray!), there are a few kinks that I need to work out. Here's a link to the test record that went through - http://vtechworks.pprd.lib.vt.edu/123456789/64486. The issues that I encountered are the following (not all-inclusive):

1) There are lots of duplicate fields - "dc.identifier.other", "dc.description.notes", "dc.title.serial", "dc.identifier.volume", "dc.identifier.issue", and "pubs.requested-embargo-period" all appear twice (and have duplicate values, not unique values).

2) I'm not sure how to capture the rights URI from the Symplectic metadata (I asked Andrew and Adrien how to do this - they haven't gotten back to me)

3) I decided to place an individual's address information into the "dc.description.notes" field, but it just looks funky. Perhaps I could instead map that information to Symplectic's "pubs.addresses" field instead - let me know what you think. 

4) I still have to address the forward slashes (e.g., "/Virginia Tech") that appear in the "pubs.organisational-group" field.

@keithgee , how do I go about making changes to the XSLT? Do I just commit new changes on GitHub, then wait for you to transfer those changes to PPRD? Thanks so much, take care.

**Comment by keithgee** [comment] 2016-04-05 11:59
@mello99, yes. Commit the changes to GitHub, and then let me know that you've done that so I can move them over to PPRD. Unfortunately, we don't have a way to test crosswalk changes for Elements on your local system right now.

In production, changes to the crosswalk, if they're ever necessary, will work the same way as other production changes. Commit new changes to GitHub during a sprint, and at the end of the sprint, Amanda will create a version of VTechWorks with the changes and work with Francis to deploy everything.

**Comment by mello99** [comment] 2016-04-05 17:23
Posted questions about these issues on Symplectic's forums:
- Duplicate metadata fields - https://support.symplectic.co.uk/support/discussions/topics/6000035125
- Forward slashes - https://support.symplectic.co.uk/support/discussions/topics/6000035126
- Creative Commons language export - https://support.symplectic.co.uk/support/discussions/topics/6000035127

**Comment by amandafrench** [comment] 2016-04-05 17:33
Great, thanks, @mello99. Make sure you mention that this is specifically for an installation of Elements 4.16 with a Repository Tools Module connecting to DSpace 5.x, too -- not all Elements installations have the Repo Tools Module, and not all of them connect to DSpace.

**Comment by mello99** [comment] 2016-04-05 18:45
I added that information to the first two postings - they haven't allowed me to comment on the third post (odd, hopefully that will change soon).

**Comment by mello99** [comment] 2016-04-05 23:31
OK, @amandafrench and @keithgee , here's the response that I got from Symplectic about the duplicates issue:

"Can you check in your dspace.cfg for following list?  All your customised new metadata field must be in that list.

If not, you have to update the list.  

```
----------------------------------------------------------------------------- 
Metadata configuration                                                     
-----------------------------------------------------------------------------  

Publications Module Authority Controlled Metadata Fields
--------------------------------------------------------
The list of metadata fields which can be authority controlled by publications
If specified, this list will form a core of metadata which may be subject
to alteration by the publications metadata feed (unless the config option
publications.metadata.update is set to false)

publications.metadata.authority-list = \
        dc.contributor.author, \
        dc.contributor.advisor, \
        dc.contributor.other, \
        dc.contributor.editor, \.......

Hope that can solve your duplicate metadata in Dspace."
```

I looked in the dspace config file and couldn't find any reference to a "pubs" or "publications" metadata authority list. Thanks, take care.

**Comment by alawvt** [comment] 2016-04-06 13:30
publications.metadata.authority-list is in append_to_dspace.cfg. It was appended to dspace.cfg on the server but not added to the GitHub repository. It matches the list there. I will email you the contents.

**Comment by keithgee** [comment] 2016-04-06 16:18
Thanks, @alawvt. I do have permission now from Symplectic to add configuration for Elements to the GitHub repository, so I will likely add this soon. It's not necessary on all of our installations, but I think it makes sense to track it the same way we track the rest of our source code, anyway. Config for pre-prod and prod will be slightly different.

**Comment by keithgee** [comment] 2016-04-06 17:52
@mello99 I added a few lines to that configuration. 
  dc.description.notes, \
        dc.title.serial, \
        dc.title.volume

I'm wondering if, when you submit again, the Journal Title field in dc.title.serial won't be duplicated. I'm not saying you need to do this now; whenever you're ready let me know. Thanks!

**Comment by mello99** [comment] 2016-04-06 20:21
Hi, @keithgee , I resubmitted an item with the "dc.title.serial" field; that field isn't duplicated, but several others are (e.g, volume and issue numbers, embargo period, etc.). "dc.description.notes" is fine - I'd like to manually upload a publication with all of the fields in it before I make a final decision on whether that's okay, though. Take care! And I will upload the article today! Thanks!

**Comment by mello99** [comment] 2016-04-06 21:03
@keithgee , you are rocking and rolling with this! The latest journal article I imported has NO duplicate metadata fields (http://vtechworks.pprd.lib.vt.edu/123456789/64494); the only fields that look close to being duplicates (and this may be a different issue altogether) are two "dc.provenance" fields (see below):

![screen shot 2016-04-06 at 4 59 45 pm](https://cloud.githubusercontent.com/assets/5408616/14332748/fd78e16a-fc18-11e5-942f-c3a925d27616.png)

The dates are technically different, but I didn't upload the publication more than once, so I'm not sure why two submission dates are being shown.

Regardless, EXCELLENT job fixing the duplicates - it looks like you found the way! I will test importing different content types (e.g., books, book chapters, artefacts, posters, etc.) to see if this issue comes up with any of those deposits. 

I don't want to close this issue until I've ensured that each of the publication types doesn't produce more duplicated fields.

Many, many thanks!!

**Comment by mello99** [comment] 2016-04-14 19:41
Hi, @keithgee , there are some ongoing duplication issues involving the Elements items being exported to PPRD (see [this item](http://vtechworks.pprd.lib.vt.edu/handle/123456789/64501)).

In short, the "dc.relation.ispartof" field is duplicated, and the "dc.format.extent" field is duplicated as well. The "dc.format.extent" field is uniquely problematic: one "dc.format.extent" field is different from the other. To elaborate, one "dc.format.extent" field only lists the item's start page, while another lists the item's start page, end page, and the total # of pages. 

I'm not sure if the "dc.format.extent" issue is caused by something that's going on in the DSpace config file, the XSLT, or if Symplectic made a change (one of their support staff mentioned that he would try to change this field so that question marks wouldn't appear if a user didn't list an item's start and end pages).

I will tell you this: the "dc.format.extent" field was not duplicated in previous Symplectic exports (here's [one record](http://vtechworks.pprd.lib.vt.edu/123456789/64494), here's [another](http://vtechworks.pprd.lib.vt.edu/handle/123456789/64493)). Granted, this most recent export is for a book, not a journal article like the others (I have no idea whether this makes a difference).

One last thing - I edited the crosswalks:dictionaries section of the XSLT; I put the end-tag for this field in the wrong place, which is why I think the Creative Commons changes didn't appear. 

Hope all is well, take care!

**Comment by mello99** [comment] 2016-04-14 20:42
@keithgee , never mind about "dc.format.extent" - there is no duplication. As it turns out, what I thought was a duplicate value was actually the number of chapters in the resource, which is one of a few fields mapped to "dc.format.extent" field. I'll let Symplectic know and hopefully they can provide more context for "dc.format.extent" regarding the # of chapters in a piece. So yes, there's nothing to do on your end vis-a-vis "dc.format.extent." Thanks!

**Comment by keithgee** [comment] 2016-04-19 22:45
I'm closing this, and we will open separate tickets for each individual issue as we notice. We have an initial version of the Elements crosswalks.

**Closed as completed by keithgee** 2016-04-19 22:45 UTC
Labels: enhancement
