### ISSUE TITLE
VTW PPRD URLs not connecting to Elements (Handle issue)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#296] opened 2016-06-16 07:00 UTC
Hi all, when I click on the link to VTW PPRD on EFARSQA for a given publication, I'm directed to a page with an error message regarding the handle service (I understand we're not technically using handles for PPRD, but there's still apparently a problem if the handle service isn't set up). Thanks, everyone.

![screen shot 2016-06-16 at 2 59 18 am](https://cloud.githubusercontent.com/assets/5408616/16108007/66ddbafe-336e-11e6-81f9-32f48e2b0e7c.png)

![screen shot 2016-06-16 at 2 58 45 am](https://cloud.githubusercontent.com/assets/5408616/16107992/49c674d8-336e-11e6-9ded-e64b39e0cb0d.png)

**Comment by amandafrench** [comment] 2016-06-16 15:32
This is by design; these links won't work on dev or pprd. Long story. :) Closing.

**Closed as completed by amandafrench** 2016-06-16 15:32 UTC
