### ISSUE TITLE
Request to enable REST and SWORDv2 in vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#564] opened 2019-04-09 18:21 UTC
Please enable REST and SWORDv2 in vtechworks6-dev. This will be necessary for Elements. Also, I would like to test the report functionality with DSpace 6 REST, https://demo.dspace.org/rest/.

**Comment by keithgee** [comment] 2019-04-10 12:36
These web apps were enabled, but there are some configuration issues that were preventing you from testing rest, and probably from testing swordv2 as well.
 
I've made some fixes for these problems on the development server this morning. I'm going to open separate issues for these problems - I think the root cause is related but I'm not positive - and leave them open with some notes so that I'll remember to come back to the issue later in the month when I have more time to spend and see if there is more work that needs to be done.

The issues are at least partially due to our usual ansible scripts not being used for the deploy process, so it's possible that once we fix the scripts for DSpace 6 no additional work will need to be done to resolve these issues.

I'll close this issue so that I can track the REST and SWORDV2 problems in separate issues.

**Comment by keithgee** [comment] 2019-04-10 12:36
Closing

**Closed as completed by keithgee** 2019-04-10 12:36 UTC
Labels: DSpace6

**Comment by alawvt** [comment] 2019-04-12 19:46
continued with #564 and #566
