### ISSUE TITLE
Can't deposit a file into VTW Dev from Elements (ed.lib.vt.edu)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#397] opened 2016-09-16 20:44 UTC
Hi all, I tried to deposit a file from Elements (ed.lib.vt.edu) into VTW Dev, but Elements keeps refreshing the page whenever I try to upload a file. So, in a nutshell, I can't actually upload a file to be deposited into VTW DEV from the ed.lib.vt.edu Elements server :(. That's the one remaining test I have. Thanks for your help, and take care.

**Comment by keithgee** [comment] 2016-09-16 21:21
I'm not sure who thought to test this, but it was a good idea. I think the problem was related to the security changes on vtechworks.dev.
I was able to duplicate this and also couldn't deposit; Elements refreshed the page when I uploaded a file, but didn't give an error message.

On ed.lib, I have access to the Elements modules control panel. Under "Module Admin -> Repository Connection -> Edit the Existing Connection", I changed the "Service base URL" from http to https.

After the change, I was successfully able to deposit. 
The setting on efarqa.lib and efars.provost is also at http. I've left it because it this will help verify it was the cause of the problem, once vtechworks.pprd and vtechworks production are also updated with new security. @amandafrench has access to change this setting to https if I am vacationing when the change is made.

*\* Closing

**Comment by mello99** [comment] 2016-09-23 14:07
This same problem is manifesting itself on PPRD (efarqa.lib.vt.edu). As a result, I can't test depositing items from Elements (efarqa.lib.vt.edu) to PPRD. Thanks.

**Comment by keithgee** [comment] 2016-09-23 15:22
I've just updated this setting on PPRD and production.

**Closed as completed** 2016-09-23 15:32 UTC
Labels: bug, support, testing
