### ISSUE TITLE
Update item usage statistics customization for DSpace 6

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#618] opened 2019-08-07 17:52 UTC
Previous issue #317 added individual download stats to each item page with PR #427. Since this relied on ID, we will need to make this work with UUID.

See also related issue, [Enable SOLR stats after migration from DSpace 5 to 6 #129](https://code.vt.edu/it-services/vtlibans_dspace/issues/129)

**Comment by alawvt** [comment] 2019-08-07 17:57
Thinking about this a bit more, I created a new item in my DSpace 6 LDE and ran the stat-util. The downloads value on the item page did increment. So, perhaps it is still able to use the ID, even for new items--must investigate.

**Comment by keithgee** [comment] 2019-08-07 18:04
This appears to me to be working with UUID after an upgrade to DSpace 6; the problem is that it no longer works with the old ID, and most of our statistics records are currently using the old ID. It should work with both.

I'm not particularly familiar with this customization, but I suspect that getting it to work with ID and UUID may require modifying the mets.xml created by Dspace to include the legacy ID. It's an option, but rather than go that route and diverge further from the core DSpace code, it might be better to use Terry's statistics update tool to see if that resolves the issue.

We've got about 77 million stats records on the dev instance; it will probably need about 24 hours to run there even if it's extremely fast. And lots of disk space, and some extra memory. Could probably figure by Monday which approach makes sense.

**Comment by keithgee** [comment] 2019-08-07 18:07
@alawvt, my instinct is that this issue is higher priority than the other two currently open issues, but let me know if that's not the case.

**Comment by alawvt** [comment] 2019-08-07 18:11
Yes, I agree this is higher priority. I wouldn't launch without this working.

**Comment by alawvt** [comment] 2019-08-07 18:14
from https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/util/SolrUpgradePre6xStatistics.java, 
```
Recommendation: for a large repository, run this command with -Xmx2000m if possible.
 * 
 * To process 1,000,000 statistics records, it took 60 min to complete.
```
So it might be 3-4 days. I'd be fine with converting all our stats to UUIDs and not have to update the customization.

**Comment by soumikgh** [comment] 2019-08-07 18:37
Keith, memory and disk space shouldn't be a problem upto a reasonble limit. If you think you need more memory or disk on dev, just let me know.

**Comment by keithgee** [comment] 2019-08-07 19:48
The original issue mentioned the DRUM repository at UMD as an example of a site with this feature. DRUM is now on version 6 of DSpace. 

I've put the DSpace 6 DRUM version of the code in branch [add_umd_bitstream_downloads_stat_dspace6](https://github.com/VTUL/vtechworks/tree/add_umd_bitstream_downloads_stat_dspace6). But DON'T merge it yet; it's not tested on a system with old stats yet, and there's no pull request.

Also, I still want try Terry's tool because I think that may be preferable. 

Edit: relevant commit - 45b5f534

**Comment by alawvt** [comment] 2019-08-07 19:51
@keithgee, thank you for researching DRUM and our options.

**Comment by keithgee** [comment] 2019-08-08 04:30
I'm still downloading the large statistics core to test Terry's statistics updater tool on my LDE, but since there's a hard storm here that may interrupt the download if I lose power, I put the University of Maryland change on the dev cloud. I think the items that still show zero may just be newer than the statistics core, but I haven't verified that. Please ignore the mysterious shrinking VTechWorks logo there for the moment; I think it's a temporary glitch.

**Comment by alawvt** [comment] 2019-08-08 17:27
With the DRUM commit, the download stats are now appearing on dev. For example, the poster child, https://vtechworks-dev.cloud.lib.vt.edu/handle/10919/18649. However, there are some peculiarities, for example the stats for the ETD community, https://vtechworks-dev.cloud.lib.vt.edu/handle/10919/5534/statistics, list total visits for 

  | Views
-- | --
ETDs: ...(legacy) | 135943
ETDs: ... | 1

Where as production running DSpace 5, https://vtechworks.lib.vt.edu/handle/10919/5534/statistics, lists, 


  | Views
-- | --
ETDs: Virginia Tech Electronic Theses and Dissertations | 208070

**Comment by keithgee** [comment] 2019-08-08 17:52
If there's an issue with those individual stats pages, it's potentially something different from the bitstream download customization in the item view.

It's potentially difficult to verify that there's an issue by comparing with the current production instance of VTechWorks, though. In our Slack chat, Soumik noted that the statistics that are on the dev server, while from PROD, are probably from sometime last year.

**Comment by keithgee** [comment] 2019-08-08 18:10
I don't know if this helps, but I believe the stats there to be from July 19, 2018.

**Comment by alawvt** [comment] 2019-08-08 18:13
I expected the numbers to be different because of the dates. I was mainly noting the cryptic categories like, "ETDs: ...(legacy)" instead of the full community name.

**Comment by keithgee** [comment] 2019-08-08 20:12
Terry's statistics updater is in branch [add_terry_brady_statistics_updater ](https://github.com/VTUL/vtechworks/tree/add_terry_brady_statistics_updater). This branch doesn't include the DRUM fixes.

I started experimenting in my VM. I wanted to start, very, very small since my VM resources - disk and memory - are limited, so I adjusted the --num-rec parameter. I noticed that if you adjust that, you should also adjust the --batch-size parameter so that it is smaller than --num-rec parameter (I've made num-rec a multiple of batch-size, plus one), otherwise it seems either no updates happen, or the output is weird at the end.

Having a small batch size probably slows things down a lot, but on the production servers where we have access to more memory and more disk space, I hope that we won't need to adjust the parameters and it will be fast. Mentioning this just in case, though.


```
vagrant@vtechworksvm:/dspace/bin$ sudo -u vtechworks ./dspace dsrun org.dspace.util.SolrUpgradePre6xStatistics --num-rec 2001 --batch-size 500
 * This process should be run iteratively over every statistics shard 
 * until there are no remaining records with legacy ids present.
 * This process can be run while the system is in use.
 * It is likely to take 1 hour/1,000,000 legacy records to be udpated.
 *
 * This process will rewrite most solr statistics records and may temporarily double 
 *	the size of your statistics repositories.  Consider optimizing your solr repos when complete.
 * -------------------------------------------------------------------
No index name provided, defaulting to : statistics
Connecting to http://localhost:8080/solr/statistics

=================================================================
	*** Statistics Records with Legacy Id ***

	  44,003,277	Bistream View
	  20,761,454	Item View
	     612,247	Community View
	     598,046	Collection View
	   6,643,384	Community Search
	   4,225,708	Collection Search
	      12,596	Unexpected Type & Full Site
	--------------------------------------
	  76,856,712	TOTAL
=================================================================

	         500  Processed... (    11 sec; 0:00:11; DB cache:      8/       8; Docs:    500)
	       1,000  Processed... (    12 sec; 0:00:24; DB cache:     14/      14; Docs:    500)
	       1,500  Processed... (    12 sec; 0:00:36; DB cache:     19/      19; Docs:    500)
	       2,000  Processed... (    12 sec; 0:00:49; DB cache:     26/      26; Docs:    500)
	       2,001      TOTAL... (    60 sec; 0:01:00; DB cache:     26/      26; Docs:      1)

=================================================================
	*** Statistics Records with Legacy Id ***

	  44,003,277	Bistream View
	  20,761,454	Item View
	     610,247	Community View
	     598,046	Collection View
	   6,643,384	Community Search
	   4,225,708	Collection Search
	      12,596	Unexpected Type & Full Site
	--------------------------------------
	  76,854,712	TOTAL
=================================================================
```

**Comment by keithgee** [comment] 2019-08-12 13:03
@alawvt, I've used the tool on the development server with the normal batch size of 10,000 records. About 5.75 million records were processed in about 28.5 hours. This was across several runs of the tool. We've got 77 million legacy records, so this will take time to run completely, and some monitoring.

My recommendation is to use the UMD version of this item usage statistics customization, so that the bitstream download statistics are available on the item pages when the upgrade to DSpace 6 is completed, but also to run the tool to convert the legacy IDs to the new format in the solr statistics records.
 
Edit: 5.75 *million* records in 28.5 hours, not 5.75 records

**Comment by alawvt** [comment] 2019-08-12 14:37
@keithgee, thank you very much for working on this. I agree with your recommendation. Please merge the Pull Requests for both fixes, when you are ready.

**Comment by keithgee** [comment] 2019-08-12 17:20
I've merged both fixes for this issue into the vt_6_x_dev branch.

***Closing

**Comment by alawvt** [comment] 2019-09-13 13:27
Downloads in DSpace 6 are adding usage to the Downloads stat on the Simple Item View, e.g. https://vtechworks.lib.vt.edu/handle/10919/93579. It is being added to "(Item) Visits" and "File Visits" in the View Usage Statistics page, e.g. https://vtechworks.lib.vt.edu/handle/10919/93579/statistics. However, there is a delay of at least 15 minutes for these stats to appear.

**Closed as completed** 2019-09-13 14:12 UTC
Labels: DSpace6

**Comment by alawvt** [comment] 2019-09-13 14:15
The stats are an unusual application of solr in that the index is updated very frequently. I think this caused some sort of performance problem for DSpace initially, so now the stats aren’t written to the index right away, but every 15 minutes or so using the solr autocommit feature.
