### ISSUE TITLE
URLs of items no longer match their original handles

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#158] opened 2016-01-06 21:57 UTC
Observed mainly in College of Science collections, also some in College of Engineering.

Example, an item by John Cairns was batch loaded to collection 10919/24287 on 20150521. It was assigned handle 10919/52378. The item now appears at URL, http://vtechworks.lib.vt.edu/handle/10919/25048, but the URI in the simple item view is still correct.
![wrongurl](https://cloud.githubusercontent.com/assets/13037168/12156044/8bffff6a-b496-11e5-8b79-65bbf5667450.png)

(KG Edit, 7AM 2016-01-07. I'm somewhat confused about the date related metadata, but other metadata/files seem to be in order for this item now. Other DSpace items - vague term today -are still problematic)

**Comment by amandafrench** [comment] 2016-01-06 22:10
Duplicate of #159, but will leave both open for now.

**Comment by keithgee** [comment] 2016-01-06 23:08
This particular item was actually first loaded into VTechWorks on 2014-01-23, according to the provenance field,  and also DSpace log files. My working hypothesis is that the handle 10919/25048 is correct, but the current identifier.uri field is incorrect.
The item appears to have been updated on 2015-12-03, but I can't see specifically what was changed. I'm still investigating.
@alawvt, where did you see the 20150521 date?

KG Edit: No matter, alawvt. At this point I wasn't realizing that the files didn't match the metadata, and also when I/you/Amanda used the word "item" there was confusion if that meant the DSpace internal item id, the identifier.uri metadata, or the handle (and of course uri and handle normally match, but not yesterday)

**Comment by keithgee** [comment] 2016-01-06 23:17
Okay, I see that an item was loaded on 20150521 to handle 10919/52378. That's  ~~the physics department annual report~~ "The interaction between a monolayer of single-molecule magnets and a metal surface -- by Barraza-Lopez" found in our "ingest/SimpleArchiveFormatBatchloads/20150521_10919_24287/item_1" directory. Looking at this, I again believe that it is the identifer.uri metadata that is incorrect, and not the handles.  **EDIT: multiple metadata fields were incorrect.**
Investigating a little bit more.

**Comment by keithgee** [comment] 2016-01-07 03:35
@mello99 is handling this issue by uploading 50 items at a time from a metadata spreadsheet that she downloaded from the collection on December 02 to restore them to the original state.
Thanks @mello99!

**Comment by alawvt** [comment] 2016-01-07 13:18
This was the metadata for that item uploaded 2015-05-21

`<?xml version="1.0" encoding="UTF-8"?><dublin_core><dcvalue element="title">The interaction between a monolayer of single-molecule magnets and a metal surface</dcvalue><dcvalue element="identifier" qualifier="doi">http://dx.doi.org/10.1063/1.2830014</dcvalue><dcvalue element="identifier" qualifier="url">http://scitation.aip.org/content/aip/journal/jap/103/7/10.1063/1.2830014</dcvalue><dcvalue element="subject">Gold</dcvalue><dcvalue element="subject">Density functional theory</dcvalue><dcvalue element="subject">Monolayers</dcvalue><dcvalue element="subject">Charge transfer</dcvalue><dcvalue element="subject">Fermi levels</dcvalue><dcvalue element="contributor" qualifier="author">Barraza-Lopez, Salvador</dcvalue><dcvalue element="contributor" qualifier="author">Avery, Michael C.</dcvalue><dcvalue element="contributor" qualifier="author">Park, Kyungwha</dcvalue><dcvalue element="contributor">Virginia Tech. Physics Department</dcvalue><dcvalue element="date" qualifier="issued">2008-04-01</dcvalue><dcvalue element="description" qualifier="abstract">We calculate within density functional theory (DFT) and the LSDA+U formalism the electronic properties of a nanostructure in which single-molecule magnets Mn(12) are adsorbed via thiol groups onto the Au(111) surface. Our DFT calculation shows 1.23 electrons being transferred from the surface to the Mn(12) molecule, dominated by the tail on the electronic charge distribution from the gold slab. LSDA+U calculations reveal that the on-site Coulomb repulsion U does not alter the direction of the electronic charge transfer obtained from DFT, because the gold Fermi level still lies above the lowest unoccupied molecular orbital (LUMO). The U term opens up the energy gap between the highest occupied molecular orbital (HOMO) and the LUMO for an isolated standard Mn(12) but it minimally affects the gap for a sulfur-terminated Mn(12). (c) 2008 American Institute of Physics.</dcvalue><dcvalue element="description" qualifier="sponsorship">Jeffress Memorial Trust</dcvalue><dcvalue element="description" qualifier="sponsorship">National Center for Supercomputing Applications. SGI Altix Linux Supercluster - Contract No. DMR060009N</dcvalue><dcvalue element="description" qualifier="sponsorship">Virginia Tech</dcvalue><dcvalue element="identifier" qualifier="citation">Barraza-Lopez, Salvador, Avery, Michael C., Park, Kyungwha (2008). The interaction between a monolayer of single-molecule magnets and a metal surface. Journal of Applied Physics, 103(7). doi: 10.1063/1.2830014</dcvalue><dcvalue element="title" qualifier="serial">Journal of Applied Physics</dcvalue><dcvalue element="identifier" qualifier="issn">0021-8979</dcvalue><dcvalue element="date" qualifier="accessed">2015-04-24</dcvalue><dcvalue element="publisher">American Institute of Physics</dcvalue><dcvalue element="format" qualifier="extent">4 pages</dcvalue><dcvalue element="format" qualifier="mimetype">application/pdf</dcvalue><dcvalue element="type" qualifier="dcmitype">Text</dcvalue><dcvalue element="type">Article</dcvalue><dcvalue element="language" qualifier="iso">en_US</dcvalue></dublin_core>`

**Comment by amandafrench** [comment] 2016-01-07 19:36
Going to close this issue: we'll handle and track it in #159. Thanks for all the investigation, everyone!

**Closed as completed by amandafrench** 2016-01-07 19:36 UTC
Labels: bug
