### ISSUE TITLE
Keywords not being exported from Elements to VTW (Efars server)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#294] opened 2016-06-15 16:54 UTC
Hi all, Ginny mentioned that during her NLI class, keyword information was not being exported from Elements to VTW (this involves the EFARS server). This issue involves the following item: http://hdl.handle.net/10919/71356

I emailed Adrienne, who authored and deposited this item, and asked her if the keywords she added appeared in the Elements record. I say this because some of the items deposited during the NLI session had keywords and some didn't, but I can't tell if certain items didn't have keywords because of a bug or because their depositor didn't add them.

This is an odd occurrence - I don't recall the keyword field ever having been a problem when I tested on ed.lib.vt.edu. Thanks everyone.

**Comment by amandafrench** [comment] 2016-06-22 19:55
Per @mello99 at today's meeting, we couldn't reproduce this issue, so we'll close it.

**Closed as completed by amandafrench** 2016-06-22 19:55 UTC
Labels: bug
