### ISSUE TITLE
vtechworks-pprd is not displaying items correctly

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#632] opened 2019-08-29 15:59 UTC
Hmmm, earlier testing this week on pprd was going pretty well. I deposited items such as https://vtechworks-pprd.cloud.lib.vt.edu/handle/10919/93178. However, now only the most recent 5 items are viewable and the other 75,604 are not listed. When you click on that item, there is no metadata, etc. However, if you select "Edit this item," all the metadata and bitstream information is listed. If you click on the bitsteam in "Edit this item" you can see the bitstream. The authorizations seem ok.

**Comment by alawvt** [comment] 2019-08-29 16:35
in dspace log are many
```
2019-08-29 01:00:17,371 ERROR org.dspace.statistics.SolrLoggerServiceImpl @ Expected mime type application/octet-stream but got text/html. <!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> {msg=SolrCore &#39;statistics&#39; is not available due to init failure: Error opening new searcher,trace=org.apache.solr.common.SolrException: SolrCore &#39;statistics&#39; is not available due to init failure: Error opening new searcher
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:745)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.solr.filters.LocalHostRestrictionFilter.doFilter(LocalHostRestrictionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:881)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:654)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:491)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
	at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1574)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1686)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:853)
	... 8 more
Caused by: java.nio.file.NoSuchFileException: &#47;dspace&#47;solr&#47;statistics&#47;data&#47;index&#47;_a.si
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:196)
	at org.apache.lucene.store.NRTCachingDirectory.openInput(NRTCachingDirectory.java:198)
	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:113)
	at org.apache.lucene.codecs.lucene46.Lucene46SegmentInfoReader.read(Lucene46SegmentInfoReader.java:51)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:359)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:462)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:923)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:769)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:458)
	at org.apache.lucene.index.IndexWriter.&lt;init&gt;(IndexWriter.java:794)
	at org.apache.solr.update.SolrIndexWriter.&lt;init&gt;(SolrIndexWriter.java:77)
	at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:64)
	at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:284)
	at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:116)
	at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1537)
	... 10 more
```
https://lucene.472066.n3.nabble.com/Expected-mime-type-application-octet-stream-but-got-text-html-td4358892.html

**Comment by alawvt** [comment] 2019-08-29 20:44
Analyzing an item page, e.g. https://vtechworks-pprd.cloud.lib.vt.edu/handle/10919/93183?XML, at the XML stage, things still look ok (see [Manakin theme tutorial](https://wiki.duraspace.org/display/DSPACE/Manakin+theme+tutorial#Manakinthemetutorial-Debuggingatvariousstagesofthethemeapplicationpipeline)). So maybe something is happening (or not) at the theme level.

I temporarily disabled vtechworks-pprd as a data source on EFARQA since it was creating one of the error messages above per request.

@soumik tried reattaching the assetstore and restarting TomCat but that didn't seem to have an effect.

I can view bitstreams from items in both assetstore and assetstore1 by using the links in "Edit this item." 

It seems like this is a theme problem because the metadata seems to all be there, e.g. https://vtechworks-pprd.cloud.lib.vt.edu/DRI/handle/10919/71805/recent-submissions.

**Comment by keithgee** [comment] 2019-08-30 02:43
Hi, @alawvt. Sorry I couldn't look at this earlier; I was unwell earlier today and didn't work much. Because this looked to be an issue only on pre-prod but no other system, I fixed it in place. If this was something that I could have reproduced on dev or on my local machine first, I would have worked there instead.

I found that there was a problem with the solr statistics core. When I looked, it was about 144kb in size. I found a 22G stats.tar file in the /dspace/solr directory and unarchived it. All 77 million "new legacy" records are there now, and everything is displaying items correctly. So the cause appears to be that the solr statistics core was corrupted or at least not as expected, but I don't know what might have happened to cause this problem initially. I would have expected DSpace to still work even if the statistics core was mostly empty and not copied over from another system(but not corrupt). And I gather the system was mostly working earlier in the week, and then broke.

I don't have access to restart Tomcat on this system, as far as I can tell, so during this fix I unarchived the statistics data while Tomcat, and thus solr, was still running. This seems like a bad practice and if any item information seems to disappear again, perhaps @soumikgh can stop Tomcat, delete the current solr/statistics directory (which I also did not do during my fix, but should have), and then expand that archive into place and make sure the permissions seem suitable.

By the way, I noticed again that the statistics, discovery, and oai cores are each being optimized at least daily from the crontab. I have a hunch that this isn't necessary and wonder if it's contributed to any of the occasional nighttime problems we've seen on the production system.

**Closing

**Closed as completed** 2019-08-30 02:44 UTC
Labels: DSpace6

**Comment by alawvt** [comment] 2019-08-30 12:48
@keithgee, thank you very much!!! The SOLR stats are now appearing, e.g. https://vtechworks-pprd.cloud.lib.vt.edu/handle/10919/18649. On Tuesday, when things seemedok, @soumikh had copied over the SOLR stats and they were untarring but hadn't appeared yet. I will re-enable pprd as a data source for Elements EFARQA and continue testing. Thank you very much for working on this and I hope you feel better.
