### ISSUE TITLE
Elements titles appear twice in item records (VTechWorks Dev)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#285] opened 2016-06-08 21:25 UTC
Hi, all, I just deposited some Elements records into VTechWorks Dev and their titles appear twice in the item records - was this planned? Below are some screenshots of what I'm referring to:

<img width="882" alt="screen shot 2016-06-08 at 5 23 43 pm" src="https://cloud.githubusercontent.com/assets/5408616/15911407/c525204c-2d9d-11e6-8e9d-926afdeb3ab3.png">

<img width="870" alt="screen shot 2016-06-08 at 5 24 39 pm" src="https://cloud.githubusercontent.com/assets/5408616/15911449/e9fee33a-2d9d-11e6-9362-79154bb01e0a.png">

<img width="883" alt="screen shot 2016-06-08 at 5 25 06 pm" src="https://cloud.githubusercontent.com/assets/5408616/15911464/f9526bea-2d9d-11e6-98ef-7fa74fefd797.png">

**Comment by alawvt** [comment] 2016-06-09 12:23
In http://vtechworks.dev.lib.vt.edu/handle/10919/71321?show=full, the dc.title field is repeated,
```
dc.subject	Criminal behavior	en_US
dc.title	In Cold Blood (Soğuk kanlılıkla)	en_US
dc.title	In Cold Blood (Soğuk kanlılıkla)	en_US
dc.type	Book	
```

**Comment by amandafrench** [comment] 2016-06-09 16:18
No, that's definitely not planned! Keep testing and troubleshooting ...

**Comment by keithgee** [comment] 2016-06-09 17:56
DSpace will show the additional title if two titles are provided.
When I delete the extra dc.title metadata field, the title is only shown once.

I'm closing this issue because it is essentially a duplicate of #286.

**Comment by keithgee** [comment] 2016-06-09 17:56
***Closing

**Closed as completed by keithgee** 2016-06-09 17:56 UTC
Labels: question

**Comment by mello99** [comment] 2016-06-09 18:35
Thank you for fixing this!
