### ISSUE TITLE
Selected item metadata is cut off on smaller computer screens

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#331] opened 2016-07-13 15:22 UTC
Hi there, I viewed an item in VTW using my Macbook Air, which has a 13" screen, and the item's metadata was cut off. Even if I expanded the screen to full-size, the full metadata still wouldn't appear:

![screen shot 2016-07-13 at 11 20 32 am](https://cloud.githubusercontent.com/assets/5408616/16808794/ed626d94-48eb-11e6-966f-694504325c16.png)

This issue did not present itself on my iMac, which has a 27" monitor. I used the same browser - Google Chrome, Version 51.0.2704.103 (64-bit) - on each computer. Thanks!

**Comment by pgray64** [comment] 2016-07-13 16:22
Reproducible via Chrome dev tools
<img width="1220" alt="screen shot 2016-07-13 at 12 22 00 pm" src="https://cloud.githubusercontent.com/assets/7339589/16811029/7a0c414a-48f4-11e6-83c2-16397bca2f83.png">

**Comment by pgray64** [comment] 2016-07-14 15:05
Addressed with pull request #332

**Comment by alawvt** [comment] 2016-07-14 15:19
In Firefox, the long URL in dc.relation.uri, http://vtechworks.lib.vt.edu/handle/10919/71779?show=full wraps properly in both a full monitor and in mobile view. In Chrome, the same URL does not wrap in either a full monitor or mobile view. It pushes the language column off the window.

I submitted an item with this long URL to the DSpace demo site, http://demo.dspace.org/xmlui/handle/10673/1252?show=full and it looks ok in Chrome. Since we altered the Full Item view in the past, you might try a much earlier commit in our repository and see whether it has this same issue.

**Comment by pgray64** [comment] 2016-07-15 13:32
You're right - turns out someone had mistakenly added a CSS class to metadata table cells that caused this issue - removed it and it displays fine now.

**Comment by pgray64** [comment] 2016-07-15 14:13
Was more than a simple revert, because parts of that added CSS class that caused the cutoff were needed. Fixed via new commits to my branch at pull request #332.

**Comment by alawvt** [comment] 2016-07-15 15:50
This probably continues Issue #138.  
Thank you, @pgray64. It seems to all work now.

**Closed as completed by alawvt** 2016-07-15 15:50 UTC
Labels: bug, koala sprint
